Repository APPS-sookmyung/2023-2-SpringCloud-Study, pull requests merged in 2023-11, with the labels that each got.

#8 [4주차 스프링 클라우드 스터디] 김진영
  김진영/apigateway-service/src/main/java/com/example/apigatewayservice/filter/CustomFilter.java
  김진영/apigateway-service/src/main/java/com/example/apigatewayservice/filter/GlobalFilter.java
  김진영/apigateway-service/src/main/java/com/example/apigatewayservice/filter/LoggingFilter.java
  김진영/apigateway-service/src/main/resources/application.yml
  김진영/discoveryservice/src/main/resources/application.yaml
  김진영/first-service/src/main/java/com/example/firstservice/FirstServiceController.java
  김진영/first-service/src/main/resources/application.yml
  김진영/second-service/src/main/java/com/example/secondservice/SecondServiceController.java
  김진영/second-service/src/main/resources/application.yml
Labels: 🕓 week 4

#9 [4주차 스프링 클라우드 스터디] 주아정
  주아정/apigateway-service/src/main/java/com/example/apigatewayservice/filter/CustomFilter.java
  주아정/apigateway-service/src/main/java/com/example/apigatewayservice/filter/GlobalFilter.java
  주아정/apigateway-service/src/main/java/com/example/apigatewayservice/filter/LoggingFilter.java
  주아정/apigateway-service/src/main/resources/application.yml
  주아정/first-service/pom.xml
  주아정/first-service/src/main/java/com/example/firstservice/FirstServiceController.java
  주아정/first-service/src/main/resources/application.yml
  주아정/second-service/pom.xml
  주아정/second-service/src/main/java/com/example/secondservice/SecondServiceController.java
  주아정/second-service/src/main/resources/application.yml
Labels: 🕓 week 4

#7 [4주차 스프링 클라우드 스터디] 오지수
  오지수/api-gateway-service/src/main/java/com/example/apigatewayservice/common/filter/CustomFilter.java
  오지수/api-gateway-service/src/main/java/com/example/apigatewayservice/common/filter/GlobalFilter.java
  오지수/api-gateway-service/src/main/java/com/example/apigatewayservice/common/filter/LoggingFilter.java
  오지수/api-gateway-service/src/main/resources/application.yml
  오지수/discoveryservice/build.gradle
  오지수/first-service/src/main/java/com/example/firstservice/controller/FirstServiceController.java
  오지수/first-service/src/main/resources/application.yml
  오지수/second-service/src/main/java/com/example/secondservice/controller/SecondServiceController.java
  오지수/second-service/src/main/resources/application.yml
Labels: 🕓 week 4

#11 [5주차 스프링 클라우드 스터디] 주아정
  주아정/user-service/pom.xml
  주아정/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  주아정/user-service/src/main/java/com/example/userservice/controller/UserController.java
  주아정/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  주아정/user-service/src/main/java/com/example/userservice/jpa/UserEntity.java
  주아정/user-service/src/main/java/com/example/userservice/jpa/UserRepository.java
  주아정/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  주아정/user-service/src/main/java/com/example/userservice/service/UserService.java
  주아정/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  주아정/user-service/src/main/java/com/example/userservice/vo/Greeting.java
  주아정/user-service/src/main/java/com/example/userservice/vo/RequestUser.java
  주아정/user-service/src/main/java/com/example/userservice/vo/ResponseUser.java
  주아정/user-service/src/main/resources/application.yml
Labels: 🕔 week 5

#12 [5주차 스프링 클라우드 스터디] 오지수
  오지수/user-service/build.gradle
  오지수/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  오지수/user-service/src/main/java/com/example/userservice/controller/UserController.java
  오지수/user-service/src/main/java/com/example/userservice/domain/UserEntity.java
  오지수/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  오지수/user-service/src/main/java/com/example/userservice/repository/UserRepository.java
  오지수/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  오지수/user-service/src/main/java/com/example/userservice/service/UserService.java
  오지수/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  오지수/user-service/src/main/java/com/example/userservice/vo/Greeting.java
  오지수/user-service/src/main/java/com/example/userservice/vo/RequestUser.java
  오지수/user-service/src/main/java/com/example/userservice/vo/ResponseUser.java
  오지수/user-service/src/main/resources/application.yml
Labels: 🕔 week 5

#10 [5주차 스프링 클라우드 스터디] 김진영
  김진영/user-service/pom.xml
  김진영/user-service/src/main/java/com/example/userservice/UserServiceApplication.java
  김진영/user-service/src/main/java/com/example/userservice/controller/UserController.java
  김진영/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  김진영/user-service/src/main/java/com/example/userservice/jpa/UserEntity.java
  김진영/user-service/src/main/java/com/example/userservice/jpa/UserRepository.java
  김진영/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  김진영/user-service/src/main/java/com/example/userservice/service/UserService.java
  김진영/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  김진영/user-service/src/main/java/com/example/userservice/vo/Greeting.java
  김진영/user-service/src/main/java/com/example/userservice/vo/RequestUser.java
  김진영/user-service/src/main/java/com/example/userservice/vo/ResponseUser.java
  김진영/user-service/src/main/resources/application.yml
Labels: 🕔 week 5

#15 [6주차 스프링 클라우드 스터디] 오지수
  오지수/api-gateway-service/src/main/resources/application.yml
  오지수/catalog-service/.gitignore
  오지수/catalog-service/.idea/.gitignore
  오지수/catalog-service/.idea/encodings.xml
  오지수/catalog-service/.idea/misc.xml
  오지수/catalog-service/.idea/vcs.xml
  오지수/catalog-service/.mvn/wrapper/maven-wrapper.jar
  오지수/catalog-service/.mvn/wrapper/maven-wrapper.properties
  오지수/catalog-service/mvnw
  오지수/catalog-service/mvnw.cmd
  오지수/catalog-service/pom.xml
  오지수/catalog-service/src/main/java/com/example/catalogservice/CatalogServiceApplication.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/controller/CatalogController.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/domain/CatalogEntity.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/dto/CatalogDto.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/repository/CatalogRepository.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/service/CatalogService.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/service/CatalogServiceImpl.java
  오지수/catalog-service/src/main/java/com/example/catalogservice/vo/ResponseCatalog.java
  오지수/catalog-service/src/main/resources/application.yml
  오지수/catalog-service/src/main/resources/data.sql
  오지수/catalog-service/src/test/java/com/example/catalogservice/CatalogServiceApplicationTests.java
  오지수/user-service/src/main/java/com/example/userservice/controller/UserController.java
  오지수/user-service/src/main/java/com/example/userservice/domain/UserEntity.java
  오지수/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  오지수/user-service/src/main/java/com/example/userservice/repository/UserRepository.java
  오지수/user-service/src/main/java/com/example/userservice/service/UserService.java
  오지수/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  오지수/user-service/src/main/java/com/example/userservice/vo/ResponseOrder.java
  오지수/user-service/src/main/java/com/example/userservice/vo/ResponseUser.java
Labels: 🕕 week 6

#13 [6주차 스프링 클라우드 스터디] 주아정
  주아정/apigateway-service/src/main/resources/application.yml
  주아정/catalog-service/.gitignore
  주아정/catalog-service/.mvn/wrapper/maven-wrapper.jar
  주아정/catalog-service/.mvn/wrapper/maven-wrapper.properties
  주아정/catalog-service/mvnw
  주아정/catalog-service/mvnw.cmd
  주아정/catalog-service/pom.xml
  주아정/catalog-service/src/main/java/com/example/catalogservice/CatalogServiceApplication.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/controller/CatalogController.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/dto/CatalogDto.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/jpa/CatalogEntity.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/jpa/CatalogRepository.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/service/CatalogService.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/service/CatalogServiceImpl.java
  주아정/catalog-service/src/main/java/com/example/catalogservice/vo/ResponseCatalog.java
  주아정/catalog-service/src/main/resources/application.yml
  주아정/catalog-service/src/main/resources/data.sql
  주아정/catalog-service/src/test/java/com/example/catalogservice/CatalogServiceApplicationTests.java
  주아정/user-service/src/main/java/com/example/userservice/controller/UserController.java
  주아정/user-service/src/main/java/com/example/userservice/dto/UserDto.java
  주아정/user-service/src/main/java/com/example/userservice/jpa/UserRepository.java
  주아정/user-service/src/main/java/com/example/userservice/service/UserService.java
  주아정/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  주아정/user-service/src/main/java/com/example/userservice/vo/ResponseOrder.java
  주아정/user-service/src/main/java/com/example/userservice/vo/ResponseUser.java
Labels: 🕕 week 6

#18 [7주차 스프링 클라우드 스터디] 오지수
  오지수/api-gateway-service/src/main/resources/application.yml
  오지수/catalog-service/.idea/misc.xml
  오지수/order-service/.gitignore
  오지수/order-service/.mvn/wrapper/maven-wrapper.jar
  오지수/order-service/.mvn/wrapper/maven-wrapper.properties
  오지수/order-service/mvnw
  오지수/order-service/mvnw.cmd
  오지수/order-service/pom.xml
  오지수/order-service/src/main/java/com/example/orderservice/OrderServiceApplication.java
  오지수/order-service/src/main/java/com/example/orderservice/controller/OrderController.java
  오지수/order-service/src/main/java/com/example/orderservice/domain/OrderEntity.java
  오지수/order-service/src/main/java/com/example/orderservice/dto/OrderDto.java
  오지수/order-service/src/main/java/com/example/orderservice/repository/OrderRepository.java
  오지수/order-service/src/main/java/com/example/orderservice/service/OrderService.java
  오지수/order-service/src/main/java/com/example/orderservice/service/OrderServiceImpl.java
  오지수/order-service/src/main/java/com/example/orderservice/vo/RequestOrder.java
  오지수/order-service/src/main/java/com/example/orderservice/vo/ResponseOrder.java
  오지수/order-service/src/main/resources/application.yml
  오지수/order-service/src/test/java/com/example/orderservice/OrderServiceApplicationTests.java
  오지수/user-service/src/main/java/com/example/userservice/repository/UserRepository.java
  오지수/user-service/src/main/java/com/example/userservice/security/AuthenticationFilter.java
  오지수/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  오지수/user-service/src/main/java/com/example/userservice/service/UserService.java
  오지수/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  오지수/user-service/src/main/java/com/example/userservice/vo/RequestLogin.java
Labels: 🕖 week 7

#16 [7주차 스프링 클라우드 스터디] 김진영
  김진영/apigateway-service/src/main/resources/application.yml
  김진영/order-service/.gitignore
  김진영/order-service/.mvn/wrapper/maven-wrapper.jar
  김진영/order-service/.mvn/wrapper/maven-wrapper.properties
  김진영/order-service/mvnw
  김진영/order-service/mvnw.cmd
  김진영/order-service/pom.xml
  김진영/order-service/src/main/java/com/example/orderservice/OrderServiceApplication.java
  김진영/order-service/src/main/java/com/example/orderservice/controller/OrderController.java
  김진영/order-service/src/main/java/com/example/orderservice/dto/OrderDto.java
  김진영/order-service/src/main/java/com/example/orderservice/jpa/OrderEntity.java
  김진영/order-service/src/main/java/com/example/orderservice/jpa/OrderRepository.java
  김진영/order-service/src/main/java/com/example/orderservice/service/OrderService.java
  김진영/order-service/src/main/java/com/example/orderservice/service/OrderServiceImpl.java
  김진영/order-service/src/main/java/com/example/orderservice/vo/RequestOrder.java
  김진영/order-service/src/main/java/com/example/orderservice/vo/ResponseOrder.java
  김진영/order-service/src/main/resources/application.yml
  김진영/order-service/src/test/java/com/example/orderservice/OrderServiceApplicationTests.java
  김진영/user-service/src/main/java/com/example/userservice/jpa/UserRepository.java
  김진영/user-service/src/main/java/com/example/userservice/security/AuthenticationFilter.java
  김진영/user-service/src/main/java/com/example/userservice/security/WebSecurity.java
  김진영/user-service/src/main/java/com/example/userservice/service/UserService.java
  김진영/user-service/src/main/java/com/example/userservice/service/UserServiceImpl.java
  김진영/user-service/src/main/java/com/example/userservice/vo/RequestLogin.java
Labels: 🕖 week 7
